# Generated by Django 3.1.1 on 2020-09-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
