# Generated by Django 3.1.1 on 2020-09-28 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_problem_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='code',
        ),
    ]
