# Generated by Django 3.0.10 on 2020-09-12 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200912_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
