version: '3.7'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.prod
        command: gunicorn coco_project.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/code/staticfiles
            - media_volume:/code/media
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on: 
            - db
    db:
        image: postgres:11.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./.env.prod.db
    redis:
        image: redis:alpine
    celery:
        build: .
        command: celery -A coco_project worker -l info
        volumes: 
            - .:/code
        links:
            - db
            - redis
        depends_on: 
            - db
            - redis
    celery-beat:
        build: .
        command: celery -A coco_project beat -l info
        volumes:
            - .:/code
        links:
            - db
            - redis
        depends_on:
            - db
            - redis
    nginx:
        build: ./nginx
        volumes:
            - static_volume:/code/staticfiles
            - media_volume:/code/media
        ports:
            - 1337:80
        depends_on:
            - web
volumes:
    postgres_data:
    static_volume:
    media_volume:

