# Generated by Django 3.1.1 on 2020-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_cover',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
