# Generated by Django 3.1.1 on 2020-09-24 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_cover',
            new_name='cover',
        ),
    ]
