# Generated by Django 3.1.1 on 2020-09-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200924_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(null=True, upload_to='blog_covers/'),
        ),
    ]
